#ifndef _GAME_SETTING_H
#define _GAME_SETTING_H

#include "App/AppSettings.h"

#define MAX_NUMBER_OF_TRIANGLES		(15)
#define LEVEL_RADIUS				(300.0f)
#define MAX_MOVE_BUTTON_HOLD_TIME	(90.0f)
#define PLAYER_ACCELERATION			(10.0f)
#define PLAYER_MAX_SPEED			(80.0f)
#define LEVEL_2_POINTS				(5000.0f)
#define LEVEL_3_POINTS				(10000.0f)
#define SHOOTING_TIMER_LV1			(300.0f)
#define SHOOTING_TIMER_LV2			(270.0f)
#define SHOOTING_TIMER_LV3			(230.0f)
#define BULLET_SPEED				(300.0f)
#define ENEMY_SPEED					(100.0f)
#define BONUS_SPEED					(100.0f)
#define ENEMY_SPAWNER_LV1			(1200.0f)
#define ENEMY_SPAWNER_LV2			(1000.0f)
#define ENEMY_SPAWNER_LV3			(600.0f)
#define BONUS_SPAWNER				(20000.0f)
#define ENEMY_ROTATION_SPEED		(0.3f)
#define ENEMY_DESTROY_POINT			(50)
#define ENEMY_DESTROY_MONEY			(100)
#define LIFE_PRICE					(2000)
#define NUKE_PRICE					(1000)
#define MAX_MONEY_LV1				(5000)
#define MAX_MONEY_LV2				(6000)
#define MAX_MONEY_LV3				(7000)
#define MAX_LIVES_LV1				(3)
#define MAX_LIVES_LV2				(4)
#define MAX_LIVES_LV3				(5)
#define MAX_NUKES_LV1				(3)
#define MAX_NUKES_LV2				(4)
#define MAX_NUKES_LV3				(5)
#define PLAYER_HIT_TIME				(3000.0f)
#define BONUS_TIME					(10000.0f)
#define APP_VIRTUAL_CENTER_X		(APP_VIRTUAL_WIDTH / 2)
#define APP_VIRTUAL_CENTER_Y		(APP_VIRTUAL_HEIGHT / 2)
#define DEBUG						(true)

#endif
